kafka:
  boot:
    server: localhost:9092
  topic:
    name: ulyTopic-kafkasender-job
    requestreply-topic: requestreply-topic
  consumer:
    group:
      id: uly-group-id
server:
  port: 9002
#logging:
#  level:
#    org.springframework.kafka: DEBUG
